# Generated by Django 4.1.4 on 2022-12-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pets',
        ),
    ]
