version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:13
    environment:
      - POSTGRES_DB=pet_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5444:5432'
    networks:
      - main_network
  app:
    build:
      context: .
      dockerfile: ./CICD/docker/Dockerfile
    ports:
      - "8000:8000"
#    in docker compose 3 the deploy limit is not working by default. Therefore one must run the up like:
#    docker compose --compatibility up -d
#    deploy:
#      resources:
#        limits:
#          cpus: "0.512"
#          memory: 1024M
    depends_on:
      - postgres
    networks:
      - main_network


networks:
  main_network: