version: "3.7"

services:
  postgres:
    restart: unless-stopped
    image: postgres:13
    environment:
      - POSTGRES_DB=pet_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5445:5432'
    volumes:
      - postgres-data-petstore-v:/var/lib/postgresql/data
    networks:
      - main_network
  app:
    build:
      context: .
      dockerfile: ./CICD/docker/Dockerfile
    image: pet_store
    ports:
      - "8000:8000"
    #    in docker compose 3 the deploy limit is not working by default. Therefore one must run the up like:
    #    docker compose --compatibility up -d
    environment:
      - STAGE_NAME=docker-local
      - SERVICE=api
    depends_on:
      - postgres
    networks:
      - main_network


networks:
  main_network:
volumes:
  postgres-data-petstore-v:

